package cn.edu.sustech.cs209.chatting.common;

public enum MsgType {
    COMMAND,TALK,REQ,TALKINGTO,GROUP_CREATE,G_TALK,G_COMMAND,G_REQ,G_CREATEGCONTROLLER,
    EXIT,EXIT_NO_KEEP,SERVER_EXIT,NOT_ALLOW_LOGIN,R_FIAL,EXIT_FROM_GROUP,FILE;
}
